### ISSUE TITLE
Widevine issue since update? 

### ISSUE THREAD

**Issue by AsHfIEXE** [glomatico/spotify-aac-downloader#81]
403 Client Error: Forbidden for url: https://gue1-spclient.spotify.com/widevine-license/v1/audio/license

```
[ERROR    14:11:47] (URL 1/2) Failed to check "true"
Traceback (most recent call last):
  File "C:\Users\Jason\AppData\Local\Programs\Python\Python311\Lib\site-packages\spotify_web_downloader\cli.py", line 392, in main
    url_info = downloader.get_url_info(url)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jason\AppData\Local\Programs\Python\Python311\Lib\site-packages\spotify_web_downloader\downloader.py", line 95, in get_url_info
    raise Exception("Invalid URL")
Exception: Invalid URL
[INFO     14:11:47] (Track 1/1 from URL 2/2) Downloading "Rise Up"
[ERROR    14:11:48] (Track 1/1 from URL 2/2) Failed to download "Rise Up"
Traceback (most recent call last):
  File "C:\Users\Jason\AppData\Local\Programs\Python\Python311\Lib\site-packages\spotify_web_downloader\spotify_api.py", line 72, in _check_response
    response.raise_for_status()
  File "C:\Users\Jason\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://gue1-spclient.spotify.com/widevine-license/v1/audio/license

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Jason\AppData\Local\Programs\Python\Python311\Lib\site-packages\spotify_web_downloader\cli.py", line 468, in main
    decryption_key = downloader_song.get_decryption_key(pssh)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jason\AppData\Local\Programs\Python\Python311\Lib\site-packages\spotify_web_downloader\downloader_song.py", line 69, in get_decryption_key
    license = self.downloader.spotify_api.get_widevine_license_music(challenge)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jason\AppData\Local\Programs\Python\Python311\Lib\site-packages\spotify_web_downloader\spotify_api.py", line 101, in get_widevine_license_music
    self._check_response(response)
  File "C:\Users\Jason\AppData\Local\Programs\Python\Python311\Lib\site-packages\spotify_web_downloader\spotify_api.py", line 74, in _check_response
    raise Exception(
Exception: Request failed with status code 403:
[INFO     14:11:48] Done (2 error(s))
```

When I go to 'https://gue1-spclient.spotify.com/widevine-license/v1/audio/license' within chrome while logged in on premium account it responds 'no token provided'  

Also, it is saying I'm using a free account when I'm premium. I logged out of my Spotify within chrome, logged back in, copied new cookie (from Open Cookies.txt extension) to cookies.txt in root of where I'm downloading but still thinks I'm on a free account

```
[WARNING  14:20:43] Free account detected, lyrics will not be downloaded
[ERROR    14:20:43] (URL 1/2) Failed to check "true"
Traceback (most recent call last):
  File "C:\Users\Jason\AppData\Local\Programs\Python\Python311\Lib\site-packages\spotify_web_downloader\cli.py", line 392, in main
    url_info = downloader.get_url_info(url)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jason\AppData\Local\Programs\Python\Python311\Lib\site-packages\spotify_web_downloader\downloader.py", line 95, in get_url_info
    raise Exception("Invalid URL")
Exception: Invalid URL
[INFO     14:20:44] (Track 1/1 from URL 2/2) Downloading "Rise Up"
[ERROR    14:20:44] (Track 1/1 from URL 2/2) Failed to download "Rise Up"
Traceback (most recent call last):
  File "C:\Users\Jason\AppData\Local\Programs\Python\Python311\Lib\site-packages\spotify_web_downloader\spotify_api.py", line 72, in _check_response
    response.raise_for_status()
  File "C:\Users\Jason\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://gue1-spclient.spotify.com/widevine-license/v1/audio/license

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Jason\AppData\Local\Programs\Python\Python311\Lib\site-packages\spotify_web_downloader\cli.py", line 468, in main
    decryption_key = downloader_song.get_decryption_key(pssh)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jason\AppData\Local\Programs\Python\Python311\Lib\site-packages\spotify_web_downloader\downloader_song.py", line 69, in get_decryption_key
    license = self.downloader.spotify_api.get_widevine_license_music(challenge)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jason\AppData\Local\Programs\Python\Python311\Lib\site-packages\spotify_web_downloader\spotify_api.py", line 101, in get_widevine_license_music
    self._check_response(response)
  File "C:\Users\Jason\AppData\Local\Programs\Python\Python311\Lib\site-packages\spotify_web_downloader\spotify_api.py", line 74, in _check_response
    raise Exception(
Exception: Request failed with status code 403:
[INFO     14:20:44] Done (2 error(s))
```

**Comment by glomatico** [comment]
You're running an old version update with pip:
```bash
pip install spotify-web-downloader -U
```
